name = "MyRegistry"
uuid = "a31f3b02-3745-45e6-b267-9f1e845fb543"
repo = "https://github.com/disberd/PersonalJuliaRegistry.git"

[packages]
0c499ce9-5070-43f6-85c8-6d9cb66e1eb8 = { name = "TelecomUtils", path = "T/TelecomUtils" }
22c7c615-cf67-4787-b800-cc81b4f1a63f = { name = "GeoGrids", path = "G/GeoGrids" }
757d3722-3ed7-41cf-92b5-8fcb89a722d0 = { name = "ActiveAntenna", path = "A/ActiveAntenna" }
b17e8be3-22c4-4c67-8193-f7322de64861 = { name = "SPATIAL", path = "S/SPATIAL" }
ed5d0301-4775-4676-b788-cf71e66ff8ed = { name = "PlutoUtils", path = "P/PlutoUtils" }
ee40d4b5-31c3-4fe2-b6cc-5ac7adf7f414 = { name = "CountriesBorders", path = "C/CountriesBorders" }
